version: "3"

volumes:
    indexer-modules:
    search:

services:
    search:
        image: elasticsearch:8.4.1
        hostname: search
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
            - xpack.security.enabled=false
            - node.name=search
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=http://localhost:9000" # Adjust the URL to match your frontend's origin
            - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
